vim.api.nvim_set_hl(0, "Pmenu", { ctermbg = 0, ctermfg = 15 })
vim.api.nvim_set_hl(0, "@comment", { ctermfg = 7 })
vim.api.nvim_set_hl(0, "@keyword", { ctermfg = 5 })
vim.api.nvim_set_hl(0, "@type", { ctermfg = 14 })
vim.api.nvim_set_hl(0, "@type.builtin", { ctermfg = 14 })
vim.api.nvim_set_hl(0, "@function", { ctermfg = 12 })
vim.api.nvim_set_hl(0, "@function.method", { ctermfg = 12 })
vim.api.nvim_set_hl(0, "@function.call", { ctermfg = 12 })
vim.api.nvim_set_hl(0, "@property", { ctermfg = 15 })
vim.api.nvim_set_hl(0, "@attribute", { ctermfg = 15 })
vim.api.nvim_set_hl(0, "@string", { ctermfg = 10 })
vim.api.nvim_set_hl(0, "@customfield", { ctermfg = 1 })
vim.api.nvim_set_hl(0, "GitGutterAdd", { ctermbg = 2, ctermfg = 2 })
vim.api.nvim_set_hl(0, "GitGutterChange", { ctermbg = 3, ctermfg = 3 })
vim.api.nvim_set_hl(0, "SnippetTabstop", { ctermbg = 0 })
vim.api.nvim_set_hl(0, "SnippetTabstopActive", { ctermbg = 0 })
